default_model_filename: "gnn_model.onnx"
platform: "onnxruntime_onnx"
input [                                 
 {  
    name: "l_x_"
    data_type: TYPE_FP32
    dims: [-1, 74 ]                    
  },
  {
  name:"l_edge_index_"
  data_type: TYPE_INT64
  dims: [ -1, -1]
  }
]
output [
 {
    name: "output"
    data_type: TYPE_FP32
    dims: [-1, 32 ]
  }
]
instance_group [{ kind: KIND_GPU }]

